### ISSUE TITLE
BitAgora BAG does not appear in My Tokens

### ISSUE THREAD

**Issue by Identity557** [vechain/my-tokens#24]
I transferred BAG to my VET address and it appears along with my other coins on the blockchain in vechain stats, however, it does not appear in My tokens.

**Comment by libotony** [comment]
Hi @Identity557, the BAG token is not able to be managed by my token nowt, it needs to be added to [token-registry](https://github.com/vechain/token-registry). We have reached out the BAG team when the token-registry is launched, we will try again.

**Comment by Identity557** [comment]
Thank you for the quick response
